### ISSUE TITLE
Jump to new bookmark (f2) is buggy

### ISSUE THREAD

**Issue by alanneese** [atom/bookmarks#69]
Create new 'Plain Text' file and add six blank lines.
Add bookmark to line 1.
Add bookmark to line 3.
Add bookmark to line 6.
At this point F2 cycles through the three bookmarks just fine.
Add bookmark to line 4.
Pressing F2 now cycles through the line 4 and line 6 only.

This is on a windows machine, Atom 1.10.

**Comment by bolinfest** [comment]
I'm on 1.10 on OS X. I have two bookmarks in a file: one on line 398 and one on 893. Hitting `F2` on either 892 or 894 takes me to 893. Hitting it again doesn't take me anywhere, so I can't get to the one on 398 unless I hit `shift-F2`.

**Comment by trvsc** [comment]
I'm on 1.9.4 / Windows. Getting the same behaviour as the OP. If you keep adding bookmarks beyond his test case, the behaviour of F2/Shift+F2 gets even more bizarre.

**Comment by 50Wliu** [comment]
Confirmed.

**Comment by rzelnik** [comment]
I am on Ubuntu, Atom 1.10.2. I also can confirm strange behaviour - some bookmarks are ignored.

**Comment by sebest** [comment]
Also, if you have bookmark in different files: switching using 'view all the bookmarks' does not work.
It only works if you select a bookmark that is in the current open file.

**Comment by HildoBijl** [comment]
Confirmed. I even have a simpler case.
- Create a two-line file.
- Set up a bookmark on line 1 first, and then on line 2. Pressing F2 (or shift-F2) will cycle between bookmarks.
- Set up a bookmark on line 2 first, and then on line 1. Pressing F2 will jump to the bookmark on line 2, while shift-F2 will jump to the bookmark on line 1.
Why this very different behavior? It doesn't make sense to me.

**Comment by trentjones21** [comment]
I am having the same problem as @HildoBijl (macOS Sierra, Atom 1.10.2)

**Comment by 50Wliu** [comment]
@as-cii This seems to have broken starting at the v0.39.0 release, which is right after you merged #53.

**Comment by revelt** [comment]
If I add two bookmarks, F2 cycling works fine. But if I add a bookmark in-between, topmost-one stops working:

![bookmarks_ignored](https://cloud.githubusercontent.com/assets/8344688/19594722/414f178c-977e-11e6-8b0a-daaaf13f627d.gif)

I'm on Atom 1.11.2 on MacOS Sierra

**Comment by sebest** [comment]
Hi @revelt,

What do you use to do these screencast? i'm looking for a tool that does print the keypress.

thanx

**Comment by revelt** [comment]
@sebest Screenflick for Mac. Really good.

**Comment by jasonstolaruk** [comment]
Does anyone know if/when this bug will be fixed? Setting a bookmark and later finding that I cannot navigate to it is a real bummer and it significantly affects my productivity. I'm considering switching to a different editor.
Or is there an alternative that provides similar functionality in Atom?
Thanks.

**Comment by revelt** [comment]
@jasonstolaruk It's a core feature, plugins won't help.

[Sublime Text](https://www.sublimetext.com/) strangely doesn't have this problem, just checked. In theory, if you ever work with large files, you need to keep Sublime Text on the side anyway since Atom is too slow. Personally I keep my snippets are on [Dash](https://kapeli.com/dash), so I don't care which code editor to use; I use both Atom and Sublime, whichever annoys me less at that moment :)

**Comment by 50Wliu** [comment]
> It's a core feature, plugins won't help.

This is incorrect as bookmarks is already a package.  Nothing is stopping you from creating, say, bookmarks-plus that fixes this issue and maybe adds extra features as well (see `markdown-preview-plus`, `autocomplete-plus` (which eventually replaced the old `autocomplete`), `vim-mode-plus`, etc).

That being said this should be looked at in the coming days.

**Comment by as-cii** [comment]
Apologies for this regression and thank you all so much for the patience! 🙇 

A fix has been merged into master and it will go out with the next stable and beta releases. 🚀

**Comment by revelt** [comment]
Awesome! 👍👍👍 🦄🦄🦄 🍻🍻🍻

**Comment by revelt** [comment]
@as-cii will this also fix #62?

**Comment by as-cii** [comment]
No, #71 addresses only the buggy behavior of jumping between bookmarks, which has been broken for a while now. A pull request for fixing #62 would be super appreciated though! ✨

**Comment by revelt** [comment]
I'm still having issues with jumping between bookmarks, using Mac `Atom 1.12.7`. On normal use F2 jumps only to bookmarks below and doesn't cycle, and Shift+F2 jumps to bookmarks above, but cycles too.

**Comment by Ben3eeE** [comment]
I believe the fix is only available in 1.13 which is currently in beta.

**Comment by mradam1977** [comment]
Yeah, bookmarks don't work very well.  I constantly have to work around the problem by moving to bookmarks that I can reach with F2, toggling them off and on again, each one in turn, then I can reach the others (the ones I didn't even toggle).
